package jfldb;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paul Holden
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class matches extends javax.swing.JFrame {

    /**
     * Creates new form matches
     */
    public Connection con;
    public Statement stmt;
    public ResultSet rs;
    
    public matches() {
        initComponents();
        DoConnect();
    }
   // public void Results(){
        

    
   // }
    public void DoConnect(){
     try {
         
         DBConnect dbc = new DBConnect();
         
            rs = dbc.connect("SELECT * FROM MATCHES");

                rs.next();
                int id_col = rs.getInt("MATCHID");
                
                String Team1 = rs.getString("TEAM1");
                String Team2 = rs.getString("TEAM2");
                String Score = rs.getString("SCORE");
                String Date = rs.getString("DATE");
            
                textTeam1.setText(Team1);
                textTeam2.setText(Team2);
                textResult.setText(Score);
                textDate.setText(Date);
            
            
        }   
        catch(SQLException err){
           JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMatches = new javax.swing.JPanel();
        textTeam1 = new javax.swing.JTextField();
        textTeam2 = new javax.swing.JTextField();
        textResult = new javax.swing.JTextField();
        LabeTeam1l = new javax.swing.JLabel();
        LabeTeam2l = new javax.swing.JLabel();
        labelResults = new javax.swing.JLabel();
        textDate = new javax.swing.JTextField();
        LabelDate = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnFirst = new javax.swing.JButton();
        BtnPrevious = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();
        BtnLast = new javax.swing.JButton();
        BtnNewRecord = new javax.swing.JButton();
        BtnSaveRecord = new javax.swing.JButton();
        BtnDeleteRecord = new javax.swing.JButton();
        BtnCancelNewRecord = new javax.swing.JButton();
        BtnUpdateRecord = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textTeam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTeam2ActionPerformed(evt);
            }
        });

        textResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResultActionPerformed(evt);
            }
        });

        LabeTeam1l.setText("Team 1");

        LabeTeam2l.setText("Team 2");

        labelResults.setText("Results");

        LabelDate.setText("Date of Match");

        jLabel1.setText("ID");

        javax.swing.GroupLayout panelMatchesLayout = new javax.swing.GroupLayout(panelMatches);
        panelMatches.setLayout(panelMatchesLayout);
        panelMatchesLayout.setHorizontalGroup(
            panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatchesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMatchesLayout.createSequentialGroup()
                        .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelMatchesLayout.createSequentialGroup()
                                    .addGap(103, 103, 103)
                                    .addComponent(textTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelMatchesLayout.createSequentialGroup()
                                    .addGap(126, 126, 126)
                                    .addComponent(labelResults)))
                            .addGroup(panelMatchesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textResult, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMatchesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LabelDate))
                            .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textTeam2)
                                .addComponent(textDate, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                        .addGap(53, 53, 53))
                    .addGroup(panelMatchesLayout.createSequentialGroup()
                        .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(LabeTeam1l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabeTeam2l)
                        .addGap(78, 78, 78))))
        );
        panelMatchesLayout.setVerticalGroup(
            panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatchesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMatchesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabeTeam1l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabeTeam2l))
                        .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMatchesLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatchesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelMatchesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelResults)
                    .addComponent(LabelDate))
                .addGap(13, 13, 13))
        );

        BtnFirst.setText("First");
        BtnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFirstActionPerformed(evt);
            }
        });

        BtnPrevious.setText("Previous");
        BtnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPreviousActionPerformed(evt);
            }
        });

        BtnNext.setText("Next");
        BtnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNextMouseClicked(evt);
            }
        });
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        BtnLast.setText("Last");
        BtnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLastActionPerformed(evt);
            }
        });

        BtnNewRecord.setText("New Record");
        BtnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewRecordActionPerformed(evt);
            }
        });

        BtnSaveRecord.setText("Save Record");
        BtnSaveRecord.setEnabled(false);
        BtnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveRecordActionPerformed(evt);
            }
        });

        BtnDeleteRecord.setText("Delete Record");
        BtnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteRecordActionPerformed(evt);
            }
        });

        BtnCancelNewRecord.setText("Cancel New Record");
        BtnCancelNewRecord.setEnabled(false);
        BtnCancelNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelNewRecordActionPerformed(evt);
            }
        });

        BtnUpdateRecord.setText("Update Record");
        BtnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnNewRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnDeleteRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnSaveRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCancelNewRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnFirst)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnNext)
                                .addGap(18, 18, 18)
                                .addComponent(BtnLast))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnUpdateRecord)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFirst)
                    .addComponent(BtnPrevious)
                    .addComponent(BtnNext)
                    .addComponent(BtnLast))
                .addGap(15, 15, 15)
                .addComponent(BtnUpdateRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSaveRecord)
                    .addComponent(BtnNewRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDeleteRecord)
                    .addComponent(BtnCancelNewRecord))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMatches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnBack)
                .addGap(194, 194, 194))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMatches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResultActionPerformed

    private void textTeam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTeam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTeam2ActionPerformed

    private void BtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLastActionPerformed
        // TODO add your handling code here:
        try{
                  
            rs.last();

                String Team1 = rs.getString("TEAM1");
                String Team2 = rs.getString("TEAM2");
                String Score = rs.getString("SCORE");
                String Date = rs.getString("DATE");
                String MatchID = rs.getString("MATCHID");

                textTeam1.setText(Team1);
                textTeam2.setText(Team2);
                textResult.setText(Score);
                textDate.setText(Date);
                textID.setText(MatchID);

            }
        catch(SQLException err){
                JOptionPane.showMessageDialog(matches.this, "Start of File");
            }
        catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnLastActionPerformed

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        // TODO add your handling code here:
          

    }//GEN-LAST:event_BtnNextActionPerformed

    private void BtnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFirstActionPerformed
        // TODO add your handling code here:
        try{
                  
            rs.first();

                String Team1 = rs.getString("TEAM1");
                String Team2 = rs.getString("TEAM2");
                String Score = rs.getString("SCORE");
                String Date = rs.getString("DATE");
                String MatchID = rs.getString("MATCHID");
                
                textTeam1.setText(Team1);
                textTeam2.setText(Team2);
                textResult.setText(Score);
                textDate.setText(Date);
                textID.setText(MatchID);
            }
        catch(SQLException err){
                JOptionPane.showMessageDialog(matches.this, "Start of File");
            }
        catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnFirstActionPerformed

    private void BtnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPreviousActionPerformed
        // TODO add your handling code here:
                try{
                  
            rs.previous();

            String Team1 = rs.getString("TEAM1");
            String Team2 = rs.getString("TEAM2");
            String Score = rs.getString("SCORE");
            String Date = rs.getString("DATE");
            String MatchID = rs.getString("MATCHID");
            textTeam1.setText(Team1);
            textTeam2.setText(Team2);
            textResult.setText(Score);
            textDate.setText(Date);
            textID.setText(MatchID);
            }
        catch(SQLException err){
                JOptionPane.showMessageDialog(matches.this, "Start of File");
            }
        catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnPreviousActionPerformed

    private void BtnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNextMouseClicked
        try{
                  
            rs.next();

                String Team1 = rs.getString("TEAM1");
                String Team2 = rs.getString("TEAM2");
                String Score = rs.getString("SCORE");
                String Date = rs.getString("DATE");
                String MatchID = rs.getString("MATCHID");
                
                textTeam1.setText(Team1);
                textTeam2.setText(Team2);
                textResult.setText(Score);
                textDate.setText(Date);
                textID.setText(MatchID);
            }
        catch(SQLException err){
                JOptionPane.showMessageDialog(matches.this, "End of File");
            }
        catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnNextMouseClicked

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
         // TODO add your handling code here:
        this.dispose();
        new MainMenu().setVisible(true);
        try{
        rs.close();
        }catch(SQLException err){
           JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewRecordActionPerformed
        // TODO add your handling code here:
           BtnFirst.setEnabled( false );
           BtnPrevious.setEnabled( false ) ;
           BtnNext.setEnabled( false );
           BtnLast.setEnabled( false );
           BtnUpdateRecord.setEnabled( false );
           BtnDeleteRecord.setEnabled( false );
           BtnNewRecord.setEnabled( false );

           BtnSaveRecord.setEnabled( true );
           BtnCancelNewRecord.setEnabled( true );
           
    }//GEN-LAST:event_BtnNewRecordActionPerformed

    private void BtnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveRecordActionPerformed
        // TODO add your handling code here:
        try{                
            rs.moveToInsertRow();
            rs.updateString("MATCHID", textID.getText());
            rs.updateString("TEAM1", textTeam1.getText());
            rs.updateString("TEAM2", textTeam2.getText());
            rs.updateString("SCORE", textResult.getText());
            rs.updateString("DATE", textDate.getText());

            
            rs.insertRow();
            
            rs.close();
            
            DBConnect db = new DBConnect();
            rs = db.connect("SELECT * FROM MATCHES");
            rs.next();
            textID.setText(rs.getString("MATCHID"));
            textTeam1.setText(rs.getString("TEAM1"));
            textTeam2.setText(rs.getString("TEAM2"));
            textResult.setText(rs.getString("SCORE"));
            textDate.setText(rs.getString("DATE"));
            }catch(SQLException err){
        JOptionPane.showMessageDialog(matches.this, err.getMessage());
        }
    }//GEN-LAST:event_BtnSaveRecordActionPerformed

    private void BtnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteRecordActionPerformed
        // TODO add your handling code here:
        try{
            rs.deleteRow();
            rs.next();       
        
        }catch(SQLException err){
        
        }
    }//GEN-LAST:event_BtnDeleteRecordActionPerformed

    private void BtnCancelNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelNewRecordActionPerformed
        // TODO add your handling code here:
        BtnFirst.setEnabled( true );
        BtnPrevious.setEnabled( true ) ;
        BtnNext.setEnabled( true );
        BtnLast.setEnabled( true );
        BtnUpdateRecord.setEnabled( true );
        BtnDeleteRecord.setEnabled( true );
        BtnNewRecord.setEnabled( true );

        BtnSaveRecord.setEnabled( false );
        BtnCancelNewRecord.setEnabled( false );
    }//GEN-LAST:event_BtnCancelNewRecordActionPerformed

    private void BtnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateRecordActionPerformed
        // TODO add your handling code here:
        String Team1 = textTeam1.getText();
        String Team2 = textTeam2.getText();
        String Result = textResult.getText();
        String Date = textDate.getText();
        
        try{
        rs.updateString("TEAM1", Team1);
        rs.updateString("TEAM2", Team2);
        rs.updateString("SCORE", Result);
        rs.updateString("DATE", Date);
        rs.updateRow();
        JOptionPane.showMessageDialog(matches.this, "Updated");

        
        }catch(Exception e){}
    }//GEN-LAST:event_BtnUpdateRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnCancelNewRecord;
    private javax.swing.JButton BtnDeleteRecord;
    private javax.swing.JButton BtnFirst;
    private javax.swing.JButton BtnLast;
    private javax.swing.JButton BtnNewRecord;
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton BtnPrevious;
    private javax.swing.JButton BtnSaveRecord;
    private javax.swing.JButton BtnUpdateRecord;
    private javax.swing.JLabel LabeTeam1l;
    private javax.swing.JLabel LabeTeam2l;
    private javax.swing.JLabel LabelDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelResults;
    private javax.swing.JPanel panelMatches;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textResult;
    private javax.swing.JTextField textTeam1;
    private javax.swing.JTextField textTeam2;
    // End of variables declaration//GEN-END:variables
}
